# -*- coding: utf-8 -*-
"""백준 4963 (섬의 개수)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wLbvuQIQ5WXpuXbv-7JmtZjUoL1OPAjK

대각선도 연결된 것으로 인정

0,0에서 부터 땅(1)이면 dfs 조지면 됨 

대각선까지 확인해야 한다.

테스트케이스를 여러개를 안해서 틀렸음
"""

"""
import sys
sys.setrecursionlimit(100000)
input = sys.stdin.readline
"""

def dfs(x, y):
    matrix[x][y] = 0
    
    dx = [1, -1, 0, 0, 1, 1, -1, -1]
    dy = [0, 0, 1, -1, 1, -1, 1, -1]

    for i in range(8):
        nx = x + dx[i]
        ny = y + dy[i]

        if (0 <= nx < h) and (0 <= ny < w):
            if matrix[nx][ny] == 1:
                dfs(nx, ny)

while True:
    w, h = map(int, input().split())
    if w == 0:
        break

    matrix = []

    for _ in range(h):
        matrix.append(list(map(int, input().split())))

    cnt = 0
    for row in range(h):
        for col in range(w):
            if matrix[row][col] == 1:
                dfs(row, col)
                cnt += 1

    print(cnt)

