# -*- coding: utf-8 -*-
"""백준 19952 (인성 문제 있어??)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J1OvrUjAf2lQqXEz4LKXYzXCI1uaMJDT
"""

from collections import deque
def bfs(x, y, f):
    q = deque()
    q.append([x,y])
    visited[x][y] = True
    while q:
        tx, ty = q.popleft()
        if tx == gx and ty == gy:
            print("잘했어!!")
            return
        for i in range(4):
            nx = tx + dx[i]
            ny = ty + dy[i]
            if 0<=nx<row and 0<=ny<col and not visited[nx][ny]:
                if (graph[nx][ny]-graph[tx][ty]) <= f:
                    q.append([nx, ny])
                    visited[nx][ny] = True
                else:
                    f -= (graph[nx][ny] - graph[tx][ty])
                    q.append([nx, ny])
                    visited[nx][ny] = True
    
    print("인성 문제있어??")
                    

t = int(input())
for _ in range(t):
    col, row, o, f, sx, sy, gx, gy = map(int, input().split())
    dx = [1, -1, 0, 0]
    dy = [0, 0, 1, -1]

    graph = [[0] * col for _ in range(row)]
    visited = [[False]*col for _ in range(row)]

    for _ in range(o):
        X, Y, n = map(int, input().split())
        graph[X-1][Y-1] = n

    bfs(sx-1, sy-1, f)

print(f)

for rows in graph:
    print(*rows)

