# -*- coding: utf-8 -*-
"""백준 9205 (맥주 마시면서 걸어가기)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ywX3S3iRjZa0RSDPyRI2e4viQeSkrzEq

- 시작점에서 편의점을 하나씩 확인하면서 간다
"""

from collections import deque
def bfs(sx, sy, gx, gy):
    q = deque()
    visited = deque()           #방문했는지 확인..
    q.append([sx, sy, 20])      #가지고있는 맥주도 저장
    
    while q:
        tx, ty, beer = q.popleft()
        if tx == gx and ty == gy:
            print("happy")
            return
        for nx, ny in store:
            if [nx, ny, 20] not in visited:
                dist = abs(nx-tx) + abs(ny-ty)
                if beer*50 >= dist:     #맥주 마시면서 갈수 있는 거리에 있으면
                    #맥주 최대로 채우기
                    q.append([nx, ny, 20])
                    visited.append([nx, ny, 20])
    print("sad")
    return
        
t = int(input())
for _ in range(t):
    n = int(input())
    store = []

    sx, sy = map(int, input().split())
    for _ in range(n):
        store.append(list(map(int, input().split())))
    gx, gy = map(int, input().split())
    store.append([gx, gy])

    bfs(sx, sy, gx, gy)