# -*- coding: utf-8 -*-
"""백준 5014 (스타트링크)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10KY1R3Vht4piOCZofa6apOqQsfry3fD_
"""

# S 와 G가 같을 때도 0이 출력되도록 해야한다

from collections import deque

def bfs(start):
    q = deque()
    q.append(s)
    visited[s] = True
    while q:
        temp = q.popleft()
        if temp == g:
            break
        for next in [temp + u, temp - d]:
            if (0<next<=f) and not visited[next]:
                floor[next] = floor[temp] + 1
                q.append(next)
                visited[next] = True


f, s, g, u, d = map(int, input().split())

if s == g:
    print(0)
else:
    floor = [0] * (f+1)
    visited = [False] * (f+1)
    bfs(s)

    if floor[g]:
        print(floor[g])
    else:
        print("use the stairs")