# -*- coding: utf-8 -*-
"""백준 2667 (단지번호붙이기)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1INATV8Z3gEkgA2NddBwXpJ6Wb-CwzlhH

유기농 배추와 비슷..
"""

from collections import deque
#import sys
#sys.setrecursionlimit(10000)

#왜 이게 되는지는 모르겟다...
def dfs(x, y, cnt):
    graph[x][y] = '0'
    #dfs 호출한 횟수가 결국 단지 내 아파트 숫자다!
    cnt += 1
    dx = [1, -1, 0, 0]
    dy = [0, 0, 1, -1]
    
    for p in range(4):  #하 상 우 좌 순서..
        nx = x + dx[p]
        ny = y + dy[p]

        if (0 <= nx < n) and (0 <= ny < n):
            if graph[nx][ny] == '1':
                #dfs를 호출할때마다 cnt를 계속 전달함
                cnt = dfs(nx, ny, cnt)
    return cnt

n = int(input())

graph = []
for _ in range(n):
    graph.append(list(input()))

dansi_num = []

for i in range(n):
    for j in range(n):
        if graph[i][j] == '1':
            cnt = 0
            cnt = dfs(i, j, cnt)
            dansi_num.append(cnt)
            #print(dansi_num)

print(len(dansi_num))
for k in sorted(dansi_num):
    print(k)