# -*- coding: utf-8 -*-
"""백준 1743 (음식물 피하기)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EDLErLTwxQRRrJ9hBwD65IZu0_GalemN
"""

from collections import deque
def bfs(x, y):
    q = deque()
    q.append([x, y])
    floor[x][y] = '.'
    cnt = 1
    while q:
        tx, ty = q.popleft()
        for p in range(4):
            nx = tx + dx[p]
            ny = ty + dy[p]
            if (0<=nx<row) and (0<=ny<col) and floor[nx][ny] == '#':
                cnt += 1
                q.append([nx, ny])
                floor[nx][ny] = '.'
    return cnt

row, col, k = map(int, input().split())
dx = [1, -1, 0, 0]
dy = [0, 0, 1, -1]

floor = [['.']*col for _ in range(row)]
for _ in range(k):
    r, c = map(int, input().split())
    floor[r-1][c-1] = '#'

size = []
for i in range(row):
    for j in range(col):
        if floor[i][j] == '#':
            size.append(bfs(i, j))
print(max(size))