# -*- coding: utf-8 -*-
"""백준 12761 (돌다리)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jwGkqJ2QOjh7r3HfHi-siatBvv4s-zv0
"""

from collections import deque

def bfs(start):
    q = deque()
    q.append(start)
    while q:
        tx = q.popleft()
        for nx in graph[tx]:
            if not path[nx]:
                q.append(nx)
                path[nx] = path[tx] + 1

a, b, n, m = map(int, input().split())

max = 100000
path = [0] * (max+1)
graph = [[] for _ in range(max+1)]

for i in range(max+1):
    #이동할 수 있는 다음 칸(연결된 위치들)
    NP = [i+1, i-1, i+a, i-a, i+b, i-b, i*a, i*b]
    for next in NP:
        if 0 <= next <= max:
            graph[i].append(next)

bfs(n)
print(path[m])