# -*- coding: utf-8 -*-
"""백준 13746 (Islands)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RX39CrJfeOJquRjWQ4T99RShpOANL_cB

- C : 구름
- W : 물
- L : 땅

-> 구름은 뭔지 모르는 것들이고, 땅일수도, 물일수도 있다..

-> 섬의 최소갯수를 구하라
"""

from collections import deque

def bfs(x, y):
    q = deque()
    q.append([x, y])
    visited[x][y] = True

    while q:
        tx, ty = q.popleft()
        for p in range(4):
            nx = tx + dx[p]
            ny = ty + dy[p]
            if (0<=nx<row) and (0<=ny<col) and not visited[nx][ny]:
                if planet[nx][ny] != 'W':
                    q.append([nx, ny])
                    visited[nx][ny] = True


row, col = map(int, input().split())
planet = [list(input()) for _ in range(row)]
visited = [[False]*col for _ in range(row)]

dx = [1, -1, 0, 0]
dy = [0, 0, 1, -1]

cnt = 0
for i in range(row):
    for j in range(col):
        if (planet[i][j] == 'L') and not visited[i][j]:
            bfs(i, j)
            cnt += 1

print(cnt)

