# -*- coding: utf-8 -*-
"""백준 2589 (보물섬)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16_Y5bka1CW5-czOKp4SBKBfh1MvXWCVl

- 브루트포스 : 모든 육지에 대해서 bfs 시도
- bfs : 최단경로 찾기
"""

from collections import deque

def bfs(x, y):
    dist = [[0]* col for _ in range(row)]
    q = deque()
    q.append([x, y])
    while q:
        tx, ty = q.popleft()
        for p in range(4):
            nx = tx + dx[p]
            ny = ty + dy[p]
            if (0<=nx<row) and (0<=ny<col) and (arr[nx][ny]=='L') and (dist[nx][ny]==0):
                dist[nx][ny] = dist[tx][ty] + 1
                q.append([nx, ny])
        
    cnt = 0
    for rows in dist:
        if cnt < max(rows):
            cnt = max(rows)
    return cnt


row, col = map(int, input().split())
arr = [list(input()) for _ in range(row)]
check = []
dx = [1, -1, 0, 0]
dy = [0, 0, 1, -1]

for i in range(row):
    for j in range(col):
        if arr[i][j] == 'L':
            check.append(bfs(i, j))

print(max(check))