# -*- coding: utf-8 -*-
"""백준 2606 (바이러스)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wPSO1mDvmqjewD9etC_V30rTpPSmGvvx

1번 컴퓨터가 바이러스에 걸렸을 때, 걸리는 컴퓨터의 갯수

#반례

- input
    - 5
    - 4 
    - 5 2
    - 4 2
    - 3 2
    - 1 2

- output
    - 1 (2번 컴퓨터)

- answer
    - 4 (2,3,4,5번 컴퓨터)
"""

from collections import deque

def bfs(graph, i, visited):
    queue = deque([i])
    cnt = 0
    visited[i] = True
    while queue:
        rear = queue.popleft()
        for k in graph[rear]:
            if not visited[k]:
                queue.append(k)
                visited[k] = True
                cnt += 1
                #print(cnt)
    print(cnt)

T = int(input())

graph = [[] for _ in range(T+1)]
visited = [False] * (T+1)
N = int(input())
for _ in range(N):
    i, j = map(int, input().split())
    graph[i].append(j)
    #양방향으로 들어왔을 때도 바이러스가 전파 되어야한다..
    if i not in graph[j]:
        graph[j].append(i)

#print(graph)
bfs(graph, 1, visited)