# -*- coding: utf-8 -*-
"""백준 7562 (나이트의 이동)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HNbxFHMXtIzHoHoHfxFTnSRjQ0T3WQex

변수의 중복사용으로 처음에 출력이 안되었다
"""

from collections import deque

def bfs(sx, sy, dest_x, dest_y):
    queue = deque()
    queue.append([sx, sy])
    while queue:
        #print(queue)
        tempx, tempy = queue.popleft()
        if (dest_x == tempx) and (dest_y == tempy):
            #print(matrix)
            print(matrix[tempx][tempy])
            return
            
        for i in range(8):
            #print(i)
            nx = tempx + dx[i]
            ny = tempy + dy[i]
            if (0 <= nx < n) and (0 <= ny < n):
                if (matrix[nx][ny] == 0):
                    queue.append([nx, ny])
                    matrix[nx][ny] = matrix[tempx][tempy] + 1
        
T = int(input())
dx = [2, 2, -2, -2, 1, 1, -1, -1]
dy = [1, -1, 1, -1, 2, -2, 2, -2]
for _ in range(T):
    n = int(input())
    start_x, start_y = map(int, input().split())
    dest_x, dest_y = map(int, input().split())
    
    matrix = [[0]*n for p in range(n)]
    bfs(start_x, start_y, dest_x, dest_y)