# -*- coding: utf-8 -*-
"""백준 14496 (그대, 그머가 되어)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DZw_LgclNhfzFu9BKn46BitSzcobWvTG
"""

from collections import deque

def bfs(start, end):
    q = deque()
    q.append(start)
    check[start] = 0
    while q:
        tx = q.popleft()
        if tx == end:
            return check[tx]

        for near in graph[tx]:
            if check[near] == -1:
                q.append(near)
                check[near] = check[tx] + 1
    return -1

a, b = map(int, input().split())
n, m = map(int, input().split())

graph = [[] for _ in range(n+1)]
check = [-1] * (n+1)        #얘로 방문여부와 거리를 다 체크한다
for _ in range(m):
    x, y = map(int, input().split())
    graph[x].append(y)
    if x not in graph[y]:
        graph[y].append(x)

print(bfs(a, b))