# -*- coding: utf-8 -*-
"""백준 11123 (양 한마리.. 양 두마리..)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LqVsh60Mv_dmJ32h4tfFcgmjzbwmFMat
"""

from collections import deque

def bfs(x, y):
    q = deque()
    q.append([x, y])
    visited[x][y] = True
    while q:
        tx, ty = q.popleft()
        for p in range(4):
            nx = tx + dx[p]
            ny = ty + dy[p]
            if (0<=nx<row) and (0<=ny<col) and not visited[nx][ny] and (field[nx][ny] == '#'):
                q.append([nx, ny])
                visited[nx][ny] = True

t = int(input())

dx = [1, -1, 0, 0]
dy = [0, 0, 1, -1]

for _ in range(t):
    row, col = map(int, input().split())
    field = [list(input()) for _ in range(row)]
    visited = [[False] * col for _ in range(row)]

    cnt = 0
    for i in range(row):
        for j in range(col):
            if not visited[i][j] and field[i][j] == '#':
                bfs(i, j)
                cnt += 1
    print(cnt)