# -*- coding: utf-8 -*-
"""백준 16928 (뱀과 사다리 게임)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hI8yPsk8QkeI_zQURti04PFp6liDmB0I

- 뱀과 사다리가 주어진다
- 1에서 100까지 가야한다
- 사다리를 만나면 올라가고, 뱀을 만나면 내려간다
"""

from collections import deque

def bfs(start):
    q = deque()
    q.append(start)
    while q:
        x = q.popleft()
        #사다리와 뱀의 칸을 잘 처리해주어야 함 (이동 횟수의 증가 없이)
        if x in ladder:
            path[ladder[x]] = path[x]
            x = ladder[x]
        if x in snake:
            path[snake[x]] = path[x]
            x = snake[x]

        for next in graph[x]:
            if path[next] == 0:
                path[next] = path[x] + 1
                q.append(next)


n, m = map(int, input().split())
graph = [[] for _ in range(101)]
ladder = {}
snake = {}

for _ in range(n):
    a, b = map(int, input().split())
    ladder[a] = b

for i in range(1, 101):
    for j in range(1,7):
        if i + j <= 100:
            graph[i].append(i+j)

for _ in range(m):
    a, b = map(int, input().split())
    snake[a] = b

path = [0] * 101
bfs(1)
print(path[100])