# -*- coding: utf-8 -*-
"""백준 1072번 (게임)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nDTMU1HxCxk5VxlilmmM8OUkvpAUISqD

**문제**

- 주어진 x(전체게임), y(이긴게임), z(승률)
- 다음부터 계속 이긴다고 할때, 승률이 변하는 순간을 구해라..

**풀이**

- 범위가 너무 커서 단순히 탐색하면 시간 초과..
- 최대판수만큼 더하면 한번은 오른다!
- 범위를 0에서 최대판수로 잡고 이분탐색..
"""

x, y = map(int, input().split())

z = 100*y // x

if z>98:
    print(-1)
else:
    #판수 범위 설정..
    start = 0
    end = 1000000000

    while (start <= end):
        mid = (start + end)//2
        if 100*(y+mid)//(x+mid) > z:
            end = mid - 1
        else:
            start = mid + 1
    print(end + 1)

