# -*- coding: utf-8 -*-
"""백준 10825 (국영수)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18AegpViJyBRY6gw1fKISDthBGxpONBgx

**문제**

- 국어점수 감소하는 순서로
    - 국어 높은 사람부터
- 국어점수 같으면 영어점수 증가하는 순서로
    - 영어 낮은 사람부터
- 국영 점수 같으면 수학점수 감소하는 순서로
    - 수학 높은 사람부터
- 모든 점수가 같으면 이름이 사전순으로 증가하는 순서로

**풀이**

- 마법의 딕셔너리..
"""

N = int(input())
scores = {}

for _ in range(N):
    name, kor, eng, math = map(str, input().split())
    scores[name] = [-int(kor), int(eng), -int(math), name]

for i in sorted(scores.values(), key=lambda x:(x[0],x[1],x[2],x[3])):
    print(i[3])