# -*- coding: utf-8 -*-
"""백준 1789 (수들의 합)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18BcxZGu-ARFXeJWl9tGOWCuD_EJyMBAb

n(n+1)/2, (n+1)(n+2)/2 사이에 있으면 n이다..
"""

N = int(input())

a = 1
while a*(a+1) / 2 <= N:
    a += 1
print(a-1)

"""하나씩 더하는 경우..

- 반례 2,5,, 등등..(97퍼에서 실패)
"""

N = int(input())

a = 1
sum = 0
while True:
    sum += a
    if N - sum < a:
        print(a)
        break
    a += 1