# -*- coding: utf-8 -*-
"""백준 2108 (통계학)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11eCbUgLxCZnY_USZt35iCf6kk8pSkTx5

**문제**

- 평균, 중앙값, 최빈값, 범위 구하기..
"""

import math

N = int(input())

nums = {}
num = []
sum = 0
for _ in range(N):
    x = int(input())
    if x in nums:
        nums[x][1] -= 1
    else:
        nums[x] = [x, -1]
    num.append(x)
    sum += x

num.sort()
Nums = sorted(nums.values(), key=lambda x : (x[1],x[0]), reverse=True)

#평균
print(round(sum/N))

#중앙값
print(num[N//2])

#최빈값
if len(Nums) == 1:
    print(num[0])
else:
    if Nums[-1][-1] < Nums[-2][-1]:
        print(Nums[-1][0])
    else:
        print(Nums[-2][0])
#범위
print(num[-1] - num[0])