# -*- coding: utf-8 -*-
"""백준 3053 (택시 기하학)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15eO8pxqZ4LlUDwU8BFUcPitPKtfkmZsW
"""

import math
r = int(input())

print(r*r*math.pi)
print(r*r*2)