# -*- coding: utf-8 -*-
"""백준 9461 (파도반 수열)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MQoqK5G75HjrwPsnaXkXe72jfhzn2Vqn

기본 수열 : 1, 1, 1, 2, 2, 3, 4, 5, 7, 9

점화식 : 초항 5개가 주어지고, $f(n+1) = f(n) + f(n-4)$
"""

T = int(input())
for _ in range(T):
    N = int(input())
    init = [0, 1, 1, 1, 2, 2]
    if N <= 5:
        print(init[N])
        continue
    else:
        for i in range(5, N):
            init.append(init[i] + init[i-4])
        print(init[N])

