# -*- coding: utf-8 -*-
"""백준 4796 (캠핑)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XxLd6YX4MoHJE7Rub-MkiL35OvZQdDsn

연속하는 8일 중에 5일만 캠핑장 사용가능.. 근데 20일 휴가가 있음..

- 20 // 8 하면 5일 연속으로 2번 이용할수 있음 -> 일단 10일 확보
- 20 % 8 이 5보다 크냐 작냐에 따라서 이용할 수 있는 날짜가 바뀜..
"""

i = 1
while True:
    L, P, V = map(int, input().split())
    if L==0:
        break

    n = (V//P) * L
    if V%P <= L:
        n += V%P
    else:
        n += L
    print(f"Case {i}: {n}")
    i += 1