# -*- coding: utf-8 -*-
"""백준 23056 (참가자 명단)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cJ1jtgmcUEKuK5jpJaWrW_YRcShCz__6

학급수 N, 학급당 신청인원 수 M

홀수팀 : 청팀, 짝수팀 : 백팀

출력순서
- 청팀 먼저, 백팀 나중에
- 각 팀에 대해서 학급을 오름차순..
- 각 학급에 대해 학생의 이름을 길이가 짧은 것 부터.. 길이가 같으면 사전순..
"""

N, M = map(int, input().split())

member = {}
num = [0 for _ in range(N)]

while True:
    a, b = map(str, input().split())
    if a == '0' and b == '0':
        break
    a = int(a)
    #[순서, 청/백팀, 학급, 길이, 이름]
    if num[a-1] < M:
        num[a-1] += 1
        member[b] = [-1* (a%2), a, len(b), b]

mem = sorted(member.values(), key = lambda x:(x[0], x[1], x[2], x[3]))
for i in mem:
    print(i[1], i[3])

