# -*- coding: utf-8 -*-
"""백준 1927 (최소 힙)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qzIKE5aSKpfPwYENHflWXFDwBWQrz1nC
"""

import heapq

nums = []
heapq.heapify(nums)
N = int(input())
for _ in range(N):
    m = int(input())
    if m == 0:
        if nums:
            print(heapq.heappop(nums))
        else:
            print(0)
    else:
        heapq.heappush(nums, m)