# -*- coding: utf-8 -*-
"""백준 1920 (수 찾기)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XNY36fjrBZZXClCbPM5KkY3ES1PZ-qRk

**문제**

- N개의 자연수가 주어지고
- M개의 자연수가 주어짐..
- M개의 자연수 중에서 N개의 자연수에 들어가는지 안들어가는지 출력하라..
"""

N = int(input())
A = list(map(int, input().split()))
A.sort()

M = int(input())
B = list(map(int, input().split()))

for i in B:
    found = False
    start, end = 0, N-1
    mid = (end+start)//2
    while start <= end:
        if i == A[mid]:
            found = True
            break
        elif i > A[mid]:
            start = mid+1
        else:
            end = mid-1
        mid = (end+start)//2
    if found:
        print(1)
    else:
        print(0)

