# -*- coding: utf-8 -*-
"""백준 20113 (긴급 회의)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kZHLr3P2AQIMiL8NYiRJ1H6FuXHATFcc
"""

N = int(input())
vote = list(map(int, input().split()))
members = {}

#초기화..
for i in vote:
    if i != 0:
        if i in members:
            members[i][1] += 1
        else:
            members[i] = [i, 1]

result = sorted(members.values(), key=lambda x :(x[1]), reverse=True)

if len(result) == 0:
    print("skipped")
elif len(result) == 1:
    print(result[0][0])
else:
    if result[0][1] == result[1][1]:
        print("skipped")
    else:
        print(result[0][0])

