# -*- coding: utf-8 -*-
"""백준 10814 (나이순 정렬)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nEatM00aNNBZknZytaLPgWT7xj11yv_W
"""

#딕셔너리 사용... 시간이 조끔 더 걸림

N = int(input())
member = {}
order = 0
for _ in range(N):
    age, name = map(str, input().split())
    member[order] = [int(age), name, order]
    order += 1
print(member)
members = sorted(member.values(), key=lambda x : (x[0], x[2]))

for i in members:
    print(i[0], i[1])

#리스트 사용.. 인덱스를 들어온 순서로 생각..
#조금 더 빠름..

N = int(input())
member = []
for _ in range(N):
    member.append(list(map(str, input().split())))
member.sort(key = lambda x: (int(x[0])))

for i in member:
    print(i[0], i[1])