# -*- coding: utf-8 -*-
"""백준 11719 (그대로 출력하기 2)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12XWKYI127KmoIFDMGKPIc8FoxidB7HpX
"""

while True:
    try:
        print(input())
    except EOFError:
        break

dsas