# -*- coding: utf-8 -*-
"""백준 1259 (팰린드롬수)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qRxBopDZvFrJBE0zKngfB7cYlG2e0szD

계속 입력받으면서 팰린드롬인지 확인
"""

while True:
    a = input()
    if a == '0':
        break
    if a == a[::-1]:
        print('yes')
    else:
        print('no')

