# -*- coding: utf-8 -*-
"""백준 4673 (셀프 넘버)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qW_kxjUQutHVka5BYWDriu3LNwKTHGm9

**풀이**

- 자료구조 셋을 이용..
"""

#수열 만들기..
def d(n):
    result = n
    for i in str(n):
        result += int(i)
    return result

dp = set(range(1, 10001))
no_self_numbers = set()

for i in range(1, 10000):
    no_self_numbers.add(d(i))

for j in sorted(list(dp.difference(no_self_numbers))):
    print(j)

