# -*- coding: utf-8 -*-
"""백준 2559번 (수열)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UgVxcp615vlDQgLes44oWGy9ceDOWm5p

**문제**

- N일 동안의 온도가 주어진다
- 연속된 K일의 온도의 합이 최대가 되는 값을 출력하라..

**풀이**

- 누적합으로 이중 for문 없이 한번만 순회하면서 계산한다
- 마지막 연속합은 따로 append 해주어야 한다
"""

N, K = map(int, input().split())
degree = list(map(int, input().split()))

degree_k = []
sum = 0
for i in range(N):
    if i < K:
        sum += degree[i]
    else:
        degree_k.append(sum)
        sum = sum - degree[i-K] + degree[i]
degree_k.append(sum)

print(max(degree_k))

