# -*- coding: utf-8 -*-
"""백준 20117 (호반우 상인의 이상한 품질 계산법)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f_lIqIF9zc7uyJAnf5qMsTtT5PigO6g-

**문제**

- 주어진 호반우를 최대한 비싸게 팔자..
- 묶음으로 팔 때는 중간값으로 생각해서 판다..

**풀이**

- 결국 2개씩 묶어서 파는게 이득이다..
- 2개씩 묶으면 큰 값으로 대체됨
"""

N = int(input())
grade = list(map(int, input().split()))
grade.sort(reverse=True)

mid = N // 2
sum = 0

for i in range(mid):
    sum += 2*grade[i]

if N % 2 ==1:
    sum += grade[mid]
    
print(sum)