# -*- coding: utf-8 -*-
"""백준 1924 (2007년)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TjDmYVOOv6yxSGyQNE7Sidj_BB6vQjg7
"""

x, y = map(int, input().split())

yoyil = {0:'MON', 1:"TUE", 2:"WED", 3:"THU", 4:"FRI", 5:"SAT", 6:"SUN"}
if x == 1:
    diff = y-1
elif x == 2:
    diff = 31 + (y-1)
elif x == 3:
    diff = 31+28+ (y-1)
elif x == 4:
    diff = 31*2 + 28 + (y-1)
elif x == 5:
    diff = 31*2 + 28 + 30 + (y-1)
elif x == 6:
    diff = 31*3 + 28+ 30 + (y-1)
elif x == 7:
    diff = 31*3 + 28 + 30*2 + (y-1)
elif x == 8:
    diff = 31*4 + 28 + 30*2 + (y-1)
elif x == 9:
    diff = 31*5 + 28 + 30*2 + (y-1)
elif x == 10:
    diff = 31*5 + 28 + 30*3 + (y-1)
elif x == 11:
    diff = 31*6 + 28 + 30*3 + (y-1)
else:
    diff = 31*6 + 28 + 30*4 + (y-1)

print(yoyil[diff%7])