# -*- coding: utf-8 -*-
"""백준 1339 (단어 수학)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wS6kGgGBnmIb4jBdlYL2ZZbr05757SLu
"""

n = int(input())
words = {}
for _ in range(n):
    num = input()
    l = len(num)
    for i in range(l):
        if num[i] in words:
            words[num[i]] += 10**(l-(i+1))
        else:
            words[num[i]] = 10**(l-(i+1))
words = sorted(words.items(), key=lambda x: x[1], reverse=True)

sum = 0
temp = 9
for s in words:
    sum += s[1] * temp
    temp -= 1
print(sum)