# -*- coding: utf-8 -*-
"""백준 18870 (좌표 압축)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10mkOF2k-0kxg7phlAkRVR2UJcJgNd3EW

**문제**

- N개의 좌표가 주어지는데, 상대적인 크기가 보존되도록 좌표를 압축해라

**풀이**

- 소팅하고
- 숫자의 종류가 몇개있나 확인한다
- 총 m개 있으면 0 ~ m-1의 숫자를 이용해서 압축

리스트에서 index() 메서드를 사용하면 다 돌아야한다..

딕셔너리에서 그냥 바로 찾도록 해주면 된다..
"""

N = int(input())

nums = list(map(int, input().split()))
nums_compressed = list(set(nums))
nums_compressed.sort()

#딕셔너리 생성.. 시간초과 해결..
compressed = {}
for i in range(len(nums_compressed)):
    compressed[nums_compressed[i]] = i

for i in nums:
    print(compressed[i], end=" ")