# -*- coding: utf-8 -*-
"""백준 1912 (연속합)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XTfH5S1PgT1j2-WtJFR2Oj7OoO-NrKAM
"""

n = int(input())
nums = list(map(int, input().split()))

dp = [0] * n
dp[0] = nums[0]

# 더한거와 그냥 원래 nums 중에 큰거를 계속 넣는게 규칙
for i in range(1, n):
    dp[i] = max(nums[i], dp[i-1] + nums[i])

print(max(dp))