# -*- coding: utf-8 -*-
"""백준 11718 (그대로 출력하기)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MlYkDFXQSOZCTZanHrBvOYIGnl8AfNgv
"""

while True:
    a = input()
    if a != '':
        print(a)
    else:
        break