# -*- coding: utf-8 -*-
"""백준 15903 (카드 합체 놀이)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qOI7T_q1LRs_svMU1wQ4Pte6i5hZNmDb
"""

import heapq

n, m = map(int, input().split())
nums = list(map(int, input().split()))
heapq.heapify(nums)     #힙으로 만들기

for _ in range(m):
    a = heapq.heappop(nums)
    b = heapq.heappop(nums)
    for i in range(2):
        heapq.heappush(nums, a+b)

print(sum(nums))