# -*- coding: utf-8 -*-
"""백준 15649 (N과 M) (1)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xsm2n-YGhLH_cVL-LGz2dh02DmtNGuZE
"""

from itertools import permutations

N, M = map(int, input().split())
n = list(range(1, N+1))

for i in permutations(n, M):
    for j in i:
        print(j, end=" ")
    print()