# -*- coding: utf-8 -*-
"""백준 11723 (집합)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c10plijJWAtNBksR4T9QJeIwzBfmS5ld

- add : 없으면 넣자
- remove : 있으면 빼자
- check : 있는지 확인하자
- toggle : 있으면 빼고 없으면 넣자
- all : 전체 집합(1~20)으로 만들자
- empty : 공집합으로 만들자

시간 절약을 위한 sys.stdin.readline().rstrip() 필수
"""

s = set()
N = int(input())
for _ in range(N):
    m = list(map(str, input().split()))
    if len(m) == 2:
        m[1] = int(m[1])
        if m[0] == 'add':
            s.add(m[1])
        elif m[0] == 'remove':
            s.discard(m[1])
        elif m[0] == 'check':
            if m[1] in s:
                print(1)
            else:
                print(0)
        elif m[0] == 'toggle':
            if m[1] in s:
                s.remove(m[1])
            else:
                s.add(m[1])
    else:
        if m[0] == 'all':
            s = set(list(range(1, 21)))
        elif m[0] == 'empty':
            s.clear()