# -*- coding: utf-8 -*-
"""백준 1748 (수 이어 쓰기 1)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10e2mkog6N_KmYtMzYCqcw3tzSpyDsaXB

**풀이**

- n의 자릿수를 구하고
- 시간 초과 방지를 위해 그냥 수식으로 계산한다
    - 자릿수 * (해당 자릿수를 가진 수의 갯수)
"""

n = int(input())
max = len(str(n))#자릿수 확인..

sum = 0
for i in range(1, max):
    sum += i * (10**i - 10**(i-1))
sum += (n+1 - 10**(max-1))*max

print(sum)