# -*- coding: utf-8 -*-
"""백준 1769 (3의 배수)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v1OPs0m8FcfP3fWPToKEzAhG2mXUFD2H

- X가 들어오면 3의 배수인지 확인하는 문제다

- 근데 주어진 문자열을 다 더해서 3의 배순지 확인하는 방법으로 푼다.

- 주어진 문자열을 다 더해보는걸 몇번해야하는지 구하라

- 내가 알고있는 3의 배수는 한 자리수 뿐이다
"""

def trans(line):
    res = 0
    for k in line:
        res += int(k)
    return str(res)

s = input()
cnt = 0

while (len(s) > 1):     #한자리 수가 될때까지 변환해본다
    s = trans(s)
    cnt += 1

print(cnt)
if int(s) % 3 == 0:
    print('YES')
else:
    print('NO')