# -*- coding: utf-8 -*-
"""백준 1946 (신입사원)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V5RjRZ43STblVP64fNfS9mBGFR4gWudQ

- 서류, 면접 성적 중 적어도 하나가 다른 지원자보다 떨어지지 않는 사람만 선발함

- 입력은 순위로 주어짐

- 선발할 수 있는 신입사원의 최대 수를 구하라

#풀이

- 첫 번째 시험 점수 기준 오름차순 정렬, 1등은 무조건 선발
- 1차 시험 1등의 두번째 시험 점수를 기준으로 다른 사람들 비교
"""

T = int(input())
for j in range(T):
    N = int(input())
    ranks = []
    for _ in range(N):
        ranks.append(list(map(int, input().split())))
    ranks = sorted(ranks, key = lambda x:x[0])

    #일차 1등은 무조건 선발
    #이차 시험의 점수를 비교
    cnt = 1
    limit = ranks[0][1]
    for i in range(1, N):
        if ranks[i][1] < limit:
            cnt += 1
            limit = ranks[i][1]

    print(cnt)