# -*- coding: utf-8 -*-
"""백준 14500 (테트로미노)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lL21drbzRk5Nkdvo2ECjUtfJXTQD5Ku2

수열을 입력받아서 순서를 바꿔가며 앞뒤 숫자의 절댓값 합의 최댓값을 출력

- permutations를 이용하여 모든 경우의 수를 계산
"""

from itertools import permutations

N = int(input())
nums = list(map(int, input().split()))

max = 0
for per in list(permutations(nums, N)):
    #print(per)
    res = 0
    for i in range(N-1):
        res += abs(per[i]-per[i+1])
    #print(res)
    if max < res:
        max = res
print(max)

