# -*- coding: utf-8 -*-
"""백준 1475 (방 번호)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15knu6SNHLmueRsdVQBSbB68u2m0phmz0

**풀이**

- 6이나 9가 있으면 세트 하나만 사도 2개 다 사용할 수 있으니 필요한 세트수를 0.5씩 증가시킨다
"""

import math
N = input()
nums = [0] * 9

for i in N:
    if i == '6' or i == '9':
        nums[6] += 0.5
    else:
        nums[int(i)] += 1
print(math.ceil(max(nums)))