# -*- coding: utf-8 -*-
"""백준 1439 (뒤집기)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jDBnYnro_cmQHNSfKex_cRAtPLv2UxIZ

11111 == 1 : 0

00000001 == 01 : 1

0001100 == 010 : 1

11001100110011000001 == 101010101 : 4

11101101 == 10101 : 2

-> 한 연속된 0, 1의 길이는 상관없다.
-> 그냥 하나라고 생각하고 바꾼 후 규칙을 보면 2로 나눈 몫이다 그냥
"""

line = input()

change_cnt = 1
for i in range(1, len(line)):
    if line[i-1] != line[i]:
        change_cnt += 1
print(change_cnt // 2)