# -*- coding: utf-8 -*-
"""백준 1699 (제곱수의 합)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K_9AzVLNCHMFiElr0Ndaj09OM0Kpq4A5
"""

# 실패
N = int(input())

cnt = 0
while True:
    cnt += 1
    temp = int(N ** 0.5)
    N -= temp**2
    if N == 0:
        print(cnt)
        break

n = int(input())

dp = [x for x in range (n+1)]       # 다 1의 제곱의 합의 갯수로 초기화
for i in range(1,n+1):
    for j in range(1,i):
        if j*j > i :
            break
        if dp[i] > dp[i-j*j] + 1 :      # 1의 합말고 다르게 더 작게 만들 수 있으면
            dp[i] = dp[i-j*j] + 1       # 바꿔줌
print(dp[n])