# -*- coding: utf-8 -*-
"""백준 1715 (카드 정렬하기)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A_2BkDpY8D5xIkMO-U2KweEOmiOJpkn7
"""

import heapq

n = int(input())

nums = []
for _ in range(n):
    nums.append(int(input()))
heapq.heapify(nums)

sum = 0
if n == 1:
    sum = 0
else:
    while True:
        a = heapq.heappop(nums)
        b = heapq.heappop(nums)
        heapq.heappush(nums, a+b)
        sum += (a+b)
        if len(nums) == 1:
            break
print(sum)