# -*- coding: utf-8 -*-
"""백준 11098 (첼시를 도와줘!)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nqzht3RzVKHriTgbMR-qFbVjbs-viuMV
"""

T = int(input())
for _ in range(T):
    players = []
    n = int(input())
    for _ in range(n):
        price, name = map(str, input().split())
        price = int(price)
        players.append([price, name])

    players.sort(key=lambda x:(x[0]), reverse=True)
    print(players[0][1])