# -*- coding: utf-8 -*-
"""백준 10162 (전자레인지)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T6CNvRB9SkgXSG-6uwl6Kng6IJECbEtu

#문제
- 5분, 1분, 10초 버튼이 있다
- 주어진 시간을 딱 맞춰서 최소버튼 조작을 하라
- 각 버튼을 누른 횟수를 각각 출력해라

#풀이
- 첫번째 while문의 조건을 T>0으로 하면 떨어지지 않는 9가 남아버리면 무한 루프에 빠짐
- 그래서 T >= 10으로 바꿈
"""

T = int(input())

times = {300 : 0, 60 : 0, 10 : 0}

while T >= 10:
    for time in times:
        while T >= time:
            T -= time
            times[time] += 1
if T == 0:
    print(*times.values())
else:
    print(-1)