# -*- coding: utf-8 -*-
"""백준 17219 (비밀번호 찾기)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YQyFZIGJkQkjMxgAIi2l4zyYYNvw4y3c
"""

N, M = map(int, input().split())

PW = {}
for _ in range(N):
    site, password = map(str, input().split())
    PW[site] = password

for _ in range(M):
    wtk = input()
    print(PW[wtk])

