# -*- coding: utf-8 -*-
"""백준 4949 (균형잡힌 세상)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vPr4hdHNzLDLbFNl3EnuVfQ2_asJFuhk

**문제**

- 소괄호, 대괄호 2종류의 괄호가 모두 균형이 잡혀야한다
- 입력의 종료조건은 맨 마지막 점 하나 (".")이다

**풀이**

- 점이 나올 때 까지 입력을 받는다
- 괄호의 짝을 알려주는 숫자를 계산한다.. (이 나오면 +1, )이 나오면 -1..
- 숫자가 음수가 되면 끝이고, 마지막에는 0이어야 한다
"""

class Stack():
    def __init__(self):
        self.items = []
    def push(self, x):
        self.items.append(x)
    def pop(self):
        if len(self.items) == 0:
            return -1
        else:
            self.items.pop()
    def top(self):
        if len(self.items) == 0:
            return -1
        else:
            return self.items[-1]
    def is_empty(self):
        if len(self.items) == 0:
            return True
        else:
            return False

while True:
    balanced = True
    sentence = input()
    stack = Stack()

    if sentence == '.':
        break
    for i in sentence:
        if i == '(' or i == '[':
            stack.push(i)
        elif i == ')':
            if stack.top() == '(':
                stack.pop()
            else:
                balanced = False
                break
        elif i == ']':
            if stack.top() == '[':
                stack.pop()
            else:
                balanced = False
                break
    if balanced and stack.is_empty():
        print("yes")
    else:
        print("no")