# -*- coding: utf-8 -*-
"""백준 11727 (2*n 타일링 2)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yed1SeBAOcyZdMrVQToF9uLI4eNgyyNd

**문제**

- 2n 타일링에서 약간 변형..

**풀이**

- 점화식 : $f(n) = f(n-1) + 2*f(n-2)$
- 2*2를 만드는 방법이 2개이다..
- 10007로 나눈 나머지..
"""

n = int(input())

a, b = 1, 3
for _ in range(n-1):
    a, b = b, b + a*2
print(a%10007)