# -*- coding: utf-8 -*-
"""백준 1543 (문서 검색)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JOI0wH2LQnm_kvg1eHiZDVYtzWZaaGJn
"""

doc = input()
target = input()
cnt = 0

# a a a a a   - 9
# a a         - 3

i = 0
for _ in range(len(doc)-len(target)+1):
    if doc[i:i+len(target)] == target:
        i += len(target)
        cnt += 1
    else:
        i += 1
    #print(i)

print(cnt)