# -*- coding: utf-8 -*-
"""백준 2920 (음계)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EnAUfbAzoIRjkgB3aFL0vOie4RMRJmNQ
"""

a = list(map(int, input().split()))
b = sorted(a, reverse=False)
c = sorted(a, reverse=True)

if a == b:
    print("ascending")
elif a == c:
    print("descending")
else:
    print("mixed")

