# -*- coding: utf-8 -*-
"""백준 9935 (문자열 폭발)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JQzROpI0Sn_EUgT198ah5y3B8lhvG9_w
"""

#시간초과..

line = input()
bomb = input()

while True:
    if bomb in line:
        line = line.replace(bomb, "")
    else:
        break
if line:
    print(line)
else:
    print('FRULA')

"""알고리즘 분류 : 자료구조, 스택

-> 입력 문자열을 스택에 넣자..

계속 넣는다..

- 스택의 size가 bomb보다 커지면 이제 비교를 해야한다
    - 마지막 거부터..
"""

#정답

line = input()
bomb = input()

stack = []

for i in line:
    stack.append(i)
    #마지막거 같고 stack에 더 많으면...
    if stack[-1] == bomb[-1] and len(stack) >= len(bomb):
        #같으면 뺀다
        if stack[-len(bomb):] == list(bomb):    #비교는 리스트로
            for _ in range(len(bomb)):
                stack.pop()

if stack:
    print("".join(stack))
else:
    print('FRULA')

bomb[-1]

"""인덱싱 연습.."""

a = 'abcdefghijklm'
b = 'jklm'

a[-4:]

a[:-4]