# -*- coding: utf-8 -*-
"""백준 25287 (순열 정렬)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z8Q2vmcA-lUKwFzY5Com_HnVj0ZikHQ0
"""

perm = list(map(int, input().split()))

N = len(perm)
mid = N/2
op = []
for i in perm:
    op.append(N-i+1)

op

mid

if N < 3:
    print("YES")
    break

res = []
smallest = -1
for i in range(N):
    if i == 0:
        res.append(min(perm[i], op[i]))
        smallest = res[i]
    else:
        if

T = int(input())
for _ in range(T):
    flag = True
    N = int(input())
    original = list(map(int, input().split()))
    if N < 3:
        print("YES")
        continue
    mid = (N+1)/2
    res = []
    temp = -1
    for i in range(N):
        if i == 0:
            if original[i] < mid:
                res.append(original[i])
                temp = res[i]
            else:
                res.append(N - original[i] + 1)
                temp = res[i]
        else:   # 들어올 수 있는 놈 중에 작은 것
            a, b = original[i], N - original[i] + 1
            # 최댓값이 temp면 감소할 수 밖에 없다
            if (a < temp) and (b < temp):
                flag = False
                break
            else:
                if a > b:
                    if b >= temp:   #작은거 먼저확인
                        # a > b >= temp
                        res.append(b)
                        temp = b
                    else:   
                        # a >= temp > b
                        res.append(a)
                        temp = a
                else:
                    if a >= temp:   #작은거 먼저확인
                        # b >= a >= temp
                        res.append(a)
                        temp = a
                    else:   
                        # b >= temp > a
                        res.append(b)
                        temp = b
    if flag:
        print("YES")
    else:
        print("NO")

import sys
input = sys.stdin.readline

T = int(input())
for _ in range(T):
    flag = True
    N = int(input())
    original = list(map(int, input().split()))
    if N < 3:
        print("YES")
        continue
    mid = (N+1)/2
    res = []
    temp = -1
    for i in range(N):
        if i == 0:
            if original[i] < mid:
                res.append(original[i])
                temp = res[i]
            else:
                res.append(N - original[i] + 1)
                temp = res[i]
        else:   # 들어올 수 있는 놈 중에 작은 것
            a, b = original[i], N - original[i] + 1
            # 최댓값이 temp면 감소할 수 밖에 없다
            if (a < temp) and (b < temp):
                flag = False
                break
            else:
                if a > b:
                    if b >= temp:   #작은거 먼저확인
                        # a > b >= temp
                        res.append(b)
                        temp = b
                    else:   
                        # a >= temp > b
                        res.append(a)
                        temp = a
                else:
                    if a >= temp:   #작은거 먼저확인
                        # b >= a >= temp
                        res.append(a)
                        temp = a
                    else:   
                        # b >= temp > a
                        res.append(b)
                        temp = b
    if flag:
        print("YES")
    else:
        print("NO")