# -*- coding: utf-8 -*-
"""백준 2164 (카드2)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RXNADD8elsEZ82VY3QlWWcSZCslp6eef

**문제**

- 1부터 N까지 카드를 순서대로 놓았다
- 카드가 한 장 남을 때까지 다음을 반복한다
    - 제일 위의 카드를 바닥에 버린다
    - 제일 위의 카드를 제일 아래로 옮긴다
"""

from collections import deque

N = int(input())
cards = deque(range(1, N+1))

while len(cards) != 1:
    cards.popleft()
    a = cards.popleft()
    cards.append(a)

print(cards[0])