# -*- coding: utf-8 -*-
"""백준 1463 (1로 만들기)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kqSfro2if6SjF_K7U5ItLJsm6tVRVOw_

**문제**

정수 X에 사용할 수 있는 연산은 다음과 같이 세 가지 이다.

- X가 3으로 나누어 떨어지면, 3으로 나눈다.
- X가 2로 나누어 떨어지면, 2로 나눈다.
- 1을 뺀다.

**풀이**
- 일단 2나 3을 나눌 수 있는 데 까지 나눈다.
- 더 이상 안 나눠지면 -1한다
- 거기서 더 한다..
"""

from collections import deque
def bfs(start):
    q = deque()
    q.append(start)
    while q:
        temp = q.popleft()
        for next in [temp+1, temp*2, temp*3]:
            if 0<=next<=max and dist[next]==0:
                dist[next] = dist[temp] + 1
                q.append(next)

max = 10**6
dist = [0] * (max + 1)

bfs(1)
n = int(input())
print(dist[n])