# -*- coding: utf-8 -*-
"""백준 5585 (거스름돈)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YbTIcesh3RPiKWdtoa--Da2dwtfE-NwW

#문제

물건을 사고 1000엔 지폐 한 장을 냄

거스름돈 종류 : 500, 100, 50, 10, 5, 1

갯수가 가장 적게 잔돈을 준다..

받을 잔돈에 포함된 잔돈의 갯수는..?

#풀이

- 리스트에 거스름돈이 비싼 순서대로 저장
- 비싼 순서대로 최대한 줌..
"""

price = int(input())
changes = [500, 100, 50, 10, 5, 1]
n = 1000 - price
cnt = 0

#거스름돈이 없을때 까지
while n != 0:     
    #비싼 순서로
    for change in changes:
        while n >= change:
            n -= change
            cnt += 1
print(cnt)