# -*- coding: utf-8 -*-
"""백준 1676

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LTUw1S8lNtA3ohr_3fvONAFIR7NHmtTp

25! : 6
26! : 6

-> 25 / 5 = 5

#풀이

- 나오는 소인수 5의 갯수를 파악하면 된다.
    - 5의 빈도수가 더 적기 때문에!
- 반복적으로 5로 나눈 몫을 더함으로서 구할 수 있다.
"""

N = int(input())

res = 0
while N > 0:
     N = N // 5
     res += N

print(res)