# -*- coding: utf-8 -*-
"""백준 11721 (열 개씩 끊어 출력하기)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uO6L-EmAovq4a5bKDhLp3YyIph1cLi6g
"""

a = input()
l = len(a)

for i in range(l):
    if i%10 == 9:
        print(a[i])
    else:
        print(a[i], end='')