# -*- coding: utf-8 -*-
"""백준 20115 (에너지 드링크)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eaIzcuFy0K5qeduY2EXkPB2h7avFqpdT

**풀이**

- 제일 큰 거에다가 계속 반 씩 부으면 된다..
"""

N = int(input())
drink = list(map(int, input().split()))
drink.sort(reverse=True)

add = 0
for i in range(1, N):
    add += drink[i]

if add % 2 == 1:
    print(drink[0] + add/2)
else:
    print(drink[0] + add//2)