# -*- coding: utf-8 -*-
"""백준 10817 (세 수)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/108WnKxjiVNEbp31NfGhEW3HjBr_b91D9
"""

a = list(map(int, input().split()))
a.sort()
print(a[1])