# -*- coding: utf-8 -*-
"""로또의 최고 순위와 최저 순위

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jjc7V3riNTvTTspczrxdZIYd6Fhh-s9m
"""

def solution(lottos, win_nums):
    zero_count = 0
    same_num = 0
    
    #0인 갯수 세기
    for i in range(len(lottos)):
        if(lottos[i] == 0):
            zero_count += 1
    
    #0포함해서 같은 갯수 세기
    for i in range(len(lottos)):
        for j in range(len(win_nums)):
            if (lottos[i] == win_nums[j]):
                same_num += 1
    
    #등수 확인..
    answer = []
    answer.append(7-same_num-zero_count)
    answer.append(7-same_num)
    if answer[0] == 7:
        answer[0] = 6
    if answer[1] == 7:
        answer[1] = 6
    
    return answer