# -*- coding: utf-8 -*-
"""소수 만들기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fRfbqOSeojU0Y9fcdKIFQkasDGmKJDs3

주어진 배열에서 3개를 선택해서 더했을 때 소수가 되는 가짓수를 세라
"""

# nC3을 어떻게 구현하는가..

# 소수 판별 함수
def Isprime(num):
    for i in range(2, int(num**(1/2)) + 1):
        if num%i == 0:
            return False
    return True

def solution(nums):
    answer = 0
    
    #nC3을 구현.. 3중 포문..
    for i in range(len(nums)-2):
        for j in range(i+1, len(nums)-1):
            for k in range(j+1, len(nums)):
                if Isprime(nums[i]+ nums[j]+ nums[k]):
                    answer += 1    
    
    return answer

#기댓값 4
print(solution([1,2,7,6,4]))

