# -*- coding: utf-8 -*-
"""음양더하기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D3kKopRPz4TgeoqxvEONNgcx4E5XD9EL
"""

def solution(absolutes, signs):
    answer = 0
    
    for i in range(len(absolutes)):
        if signs[i]:
            answer += absolutes[i]
        else:
            answer -= absolutes[i]
    return answer